name: build_windows_premake

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Generate Project Files
      run: ./Scripts/WindowsGenProjectsCMake.bat

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Solution
      run: |
        cd build
        msbuild -property:Configuration=Release,MultiProcessorCompilation=true -maxCpuCount -verbosity:minimal -noLogo Spike.sln